[mypy]
ignore_missing_imports = True
follow_imports = skip

[mypy-sg_terra.topo.depth_anything_v2.*]
ignore_errors = True

[mypy-sg_terra.seg.sam2_wrapper]
ignore_errors = True

[mypy-sg_terra.topo.depth_wrapper]
ignore_errors = True
